[project]
name = "god"
version = "0.1.0"
description = "deep ML"
readme = "README.md"
authors = [{ name = "Simon Walker", email = "simon@simonwalker.tech" }]
requires-python = ">=3.13"
dependencies = [
  "einx>=0.4.3",
  "equinox>=0.13.8",
  "jax>=0.11.1",
  "jax[cuda]>=0.11.1 ; sys_platform == 'linux'",
  "jaxtyping>=0.3.11",
  "jpc",
  "matplotlib>=3.11.1",
  "numpy>=2.5.2",
  "optax>=0.2.8",
  "plotext>=6.0.0",
  "pytest>=9.1.1",
  "scikit-learn>=1.9.0",
  "scipy>=1.18.1",
  "scipy-stubs>=1.18.1.0",
  "seaborn>=0.13.2",
  "statistics>=1.0.3.5",
  "tqdm>=4.70.0",
]

[project.scripts]
god-mlp = "god.training.mlp:main"
god-mlp-grokk = "god.training.mlp:main_grokk"
god-pcn = "god.training.pcn:main"
god-hnn = "god.training.hnn:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
jpc = { git = "https://github.com/simondoesstuff/jpc" }

[tool.pyright]
typeCheckingMode = "standard"
reportUnknownMemberType = "none"
reportAny = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportUnknownLambdaType = "none"
reportMissingTypeStubs = "none"
reportPrivateImportUsage = "none"
reportUnusedCallResult = "none"
