"""HyperNetwork grokking: modular addition via generated target classifiers.

Applies a HyperNetwork (HNN) to (a+b) mod 97 to establish a grokking baseline.
The stimulus FFN maps noise x ~ U[-1,1]^n_stimulus to the weights of a small
target FFN classifier. n_mc noise vectors are sampled each step; the loss is the
**softmax-weighted sum of per-x cross-entropy** (focuses gradient on the
worst-performing x) plus a **softmin-weighted sum of per-x target complexity**
(focuses gradient on the simplest target network).

Both weighting schemes standardise their inputs per-batch before the softmax so
that the temperature parameter `softmax_temp` / `softmin_temp` is scale-free and
behaves consistently regardless of how large the norms or CE values are.

With lambda_complexity > 0 the optimizer balances:
  - minimising the worst-case error across x samples
  - shrinking the best-case target network complexity
This decouples error and complexity optimisation without explicit WD on the HNN
or any post-step shrinkage — `lambda_complexity` is the primary grokking knob.

Key knobs:
  lambda_complexity  — weight for softmin complexity term (replaces wd_output_layer)
  softmax_temp       — sharpness of error weighting (→0 = hard worst-x focus)
  softmin_temp       — sharpness of complexity weighting (→0 = hard min-complexity)
  train_fraction     — lower → slower grok (less signal for generalisation)
  target_hidden      — larger → more capacity, longer grok

Ablation knobs (see docs/hnn_dynamics.md):
  output_bias        — False removes the stimulus FFN's final-layer bias, so
                        every generated target param must flow through the
                        x-dependent pathway (no free x-independent copy).
  shrink_target/wd    — post-step multiplicative shrinkage on
                        stimulus_ffn.layers[-1], bypassing Adam:
                        "bias" (the x-independent copy), "weight" (the
                        x-dependent carrier — required when output_bias=False),
                        or "both" (reproduces the historical wd_output_layer).
  probe_n/probe_seed  — fixed diagnostic x-probe set, independent of training
                        x, for cross-run comparable param_std/bias/residual
                        norm decomposition (logged as probe_* metrics).

Entry points:
  god-grokking-hnn       — 200k epochs (full grok)
  god-grokking-hnn-cont  — continue from checkpoint
"""

import dataclasses
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import equinox as eqx
import jax
import jax.numpy as jnp
import numpy as np
import optax
from tqdm import trange

from god.datasets.modular import ModularConfig, Op, input_dim, make_modular_dataset
from god.models.modular_hnn import ModularHNN, make_modular_hypernetwork, n_trainable_params


@dataclass
class GrokkingHNNConfig:
    data_dir: str = "data/grokking_hnn"

    # Target FFN (generated by stimulus FFN)
    target_hidden: int = 32
    target_depth: int = 1

    # Stimulus FFN (learnable HNN weights)
    n_stimulus: int = 8
    stim_ffn_hidden: int = 8
    stim_ffn_depth: int = 1
    init_scale: float = 0.1
    output_bias: bool = True  # False = no bias on stimulus_ffn's final layer

    # Data
    modulus: int = 97
    train_fraction: float = 0.5

    # Training — full-batch Adam + gradient clipping
    n_epochs: int = 200_000
    lr: float = 1e-3
    weight_decay: float = 0.0   # no WD on HNN; stability comes from grad clipping
    grad_clip: float = 1.0      # global norm clip

    # Decoupled complexity regularisation
    # Loss = softmax_error(x) + lambda_complexity * softmin_complexity(x)
    # lambda_complexity is the primary grokking knob (replaces wd_output_layer)
    lambda_complexity: float = 1e-2
    softmax_temp: float = 1.0   # error weighting sharpness
    softmin_temp: float = 1.0   # complexity weighting sharpness

    # Legacy: L2 on generated target params (loss term)
    lambda_target_decay: float = 0.0

    # Post-step multiplicative shrinkage on stimulus_ffn.layers[-1], bypassing
    # Adam (true AdamW-style WD applied directly to the chosen carrier of the
    # generated target params). "bias" isolates the x-independent copy Adam
    # tends to hide in; "weight" shrinks the x-dependent pathway (the only
    # option when output_bias=False); "both" reproduces the historical
    # wd_output_layer mechanism; "none" disables this (default).
    shrink_target: str = "none"  # "none" | "bias" | "weight" | "both"
    shrink_wd: float = 0.0

    # MC noise samples per step — drives the per-x diversity
    n_mc: int = 4
    # If True, sample x once at init and reuse every step
    fixed_x: bool = False

    # Fixed diagnostic probe set of x — independent of training x and of
    # `fixed_x`/`seed`, identical across runs for cross-run comparability.
    # Used to decompose generated target params into bias vs x-dependent
    # (residual) norm, and to measure true diversity even when fixed_x=True.
    probe_n: int = 32
    probe_seed: int = 12345

    # Logging
    log_interval: int = 2000
    hexplot_interval: int = 20_000   # 0 = disabled
    checkpoint_interval: int = 0     # 0 = disabled; saves checkpoint_{epoch:07d}.eqx
    # Fixed axis ranges so all hexplots in a run are directly comparable.
    # Complexity axis: set to cover the expected Fourier-solution norm (~193).
    # CE axis: log(97)≈4.6 is chance; 0 means auto (not recommended for sweeps).
    hexplot_xlim: float = 1000.0
    hexplot_ylim: float = 5.0

    # Reproducibility
    seed: int = 0

    def __post_init__(self) -> None:
        if self.shrink_target not in ("none", "bias", "weight", "both"):
            raise ValueError(f"shrink_target must be none/bias/weight/both, got {self.shrink_target!r}")
        if self.shrink_target in ("bias", "both") and not self.output_bias:
            raise ValueError("shrink_target requires output_bias=True to shrink a bias that doesn't exist")
        if self.shrink_target != "none" and self.shrink_wd <= 0.0:
            raise ValueError(f"shrink_target={self.shrink_target!r} but shrink_wd={self.shrink_wd} (must be > 0)")


def _loss_and_metrics(
    model: ModularHNN,
    inputs: jax.Array,
    targets: jax.Array,
    x_samples: jax.Array,
    lambda_target_decay: float = 0.0,
    lambda_complexity: float = 0.0,
    softmax_temp: float = 1.0,
    softmin_temp: float = 1.0,
) -> tuple[jax.Array, jax.Array, jax.Array]:
    """Returns (loss, mean_accuracy, mean_ce_loss).

    Loss = softmax_weighted(CE) + lambda_complexity * softmin_weighted(norm)

    Softmax over per-x errors focuses gradient on the worst-performing x.
    Softmin over per-x target norms rewards the simplest target network.
    Inputs are z-scored per batch so temperature is scale-free throughout
    training. stop_gradient is applied to the weights — without it the
    softmax term would *increase* below-average errors.
    """

    def per_x(x: jax.Array) -> tuple[jax.Array, jax.Array, jax.Array]:
        logits = jax.vmap(model, in_axes=(0, None))(inputs, x)
        ce = jnp.mean(optax.softmax_cross_entropy_with_integer_labels(logits, targets))
        acc = jnp.mean(jnp.argmax(logits, axis=-1) == targets)
        complexity = jnp.linalg.norm(model.target_params(x))
        return ce, acc, complexity

    ces, accs, complexities = jax.vmap(per_x)(x_samples)  # (n_mc,) each
    mean_ce = jnp.mean(ces)
    mean_acc = jnp.mean(accs)

    # Standardise per-batch so temperature is scale-free
    ces_norm = (ces - ces.mean()) / (ces.std() + 1e-6)
    err_w = jax.lax.stop_gradient(jax.nn.softmax(ces_norm / softmax_temp))
    weighted_error = jnp.dot(err_w, ces)

    cpx_norm = (complexities - complexities.mean()) / (complexities.std() + 1e-6)
    cpx_w = jax.lax.stop_gradient(jax.nn.softmax(-cpx_norm / softmin_temp))
    weighted_complexity = jnp.dot(cpx_w, complexities)

    loss = weighted_error + lambda_complexity * weighted_complexity

    if lambda_target_decay > 0.0:
        l2 = jnp.mean(jax.vmap(lambda x: jnp.mean(model.target_params(x) ** 2))(x_samples))
        loss = loss + lambda_target_decay * l2

    return loss, mean_acc, mean_ce


def _param_std(model: ModularHNN, x_samples: jax.Array) -> float:
    """Std of generated target params across x_samples — measures stimulus collapse."""
    all_params = jax.vmap(model.target_params)(x_samples)
    return float(jnp.mean(jnp.std(all_params, axis=0)))


def _param_norm(model: ModularHNN, x_samples: jax.Array) -> float:
    """Mean L2 norm of generated target params across x_samples."""
    all_params = jax.vmap(model.target_params)(x_samples)
    return float(jnp.mean(jnp.linalg.norm(all_params, axis=1)))


def _probe_metrics(model: ModularHNN, probe_x: jax.Array) -> dict[str, float]:
    """Diagnostics on a fixed probe x set (independent of training/fixed_x).

    Decomposes generated target params into the x-independent bias component
    and the x-dependent residual (target_params(x) - bias), so bias-vs-weight
    shrinkage effects are directly comparable across arms with/without a bias.
    """
    all_params = jax.vmap(model.target_params)(probe_x)  # (probe_n, n_params)
    total_norm = float(jnp.mean(jnp.linalg.norm(all_params, axis=1)))
    total_std = float(jnp.mean(jnp.std(all_params, axis=0)))

    bias = model.stimulus_ffn.layers[-1].bias
    if bias is not None:
        bias_norm = float(jnp.linalg.norm(bias))
        residual = all_params - bias[None, :]
    else:
        bias_norm = 0.0
        residual = all_params

    residual_norm = float(jnp.mean(jnp.linalg.norm(residual, axis=1)))
    return {
        "probe_param_norm": total_norm,
        "probe_param_std": total_std,
        "probe_bias_norm": bias_norm,
        "probe_residual_norm": residual_norm,
    }


def _plot(metrics: list[dict[str, Any]], out_path: Path) -> None:
    import matplotlib.pyplot as plt

    epochs = [m["epoch"] for m in metrics]
    train_acc = [m["train_acc"] for m in metrics]
    test_acc = [m["test_acc"] for m in metrics]
    has_diversity = "param_std" in metrics[0]

    n_rows = 2 if has_diversity else 1
    fig, axes = plt.subplots(n_rows, 1, figsize=(10, 4 * n_rows), squeeze=False)
    ax = axes[0, 0]

    ax.plot(epochs, train_acc, label="train accuracy", lw=1.5, color="tab:blue")
    ax.plot(epochs, test_acc, label="test accuracy (mean over x)", lw=1.5, color="tab:orange")
    if has_diversity:
        test_min = [m.get("test_acc_min", m["test_acc"]) for m in metrics]
        test_max = [m.get("test_acc_max", m["test_acc"]) for m in metrics]
        ax.fill_between(epochs, test_min, test_max, alpha=0.2, color="tab:orange", label="test acc min–max over x")
    ax.set_xscale("log")
    ax.set_ylim(-0.02, 1.02)
    ax.set_ylabel("accuracy")
    ax.set_title("Grokking HNN — (a+b) mod 97")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    if has_diversity:
        ax2 = axes[1, 0]
        ax2.plot(epochs, [m["param_std"] for m in metrics], lw=1.5, color="tab:purple")
        ax2.set_xscale("log")
        ax2.set_xlabel("epoch (log scale)")
        ax2.set_ylabel("param std across x")
        ax2.set_title("Target network diversity (→0 = collapsed to single solution)")
        ax2.grid(True, alpha=0.3)
    else:
        axes[0, 0].set_xlabel("epoch (log scale)")

    plt.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(str(out_path), dpi=150)
    plt.close(fig)


def _hexplot(
    model: ModularHNN,
    dataset: Any,
    n_stimulus: int,
    epoch: int,
    out_dir: Path,
    n_samples: int = 500,
    xlim: float = 1000.0,
    ylim: float = 5.0,
) -> None:
    """Hexbin of (target complexity, train CE) over random x samples.

    Complexity axis is log-scaled so init (pnorm~3) and grokking (~193) and
    collapsed-WD (~500+) regimes are all visible in the same plot.
    xlim/ylim are fixed across all calls so hexplots in a run are comparable.
    """
    import matplotlib.pyplot as plt

    key = jax.random.PRNGKey(epoch)
    x_samples = jax.random.uniform(key, (n_samples, n_stimulus), minval=-1.0, maxval=1.0)

    @eqx.filter_jit
    def _batch_metrics(xs: jax.Array) -> tuple[jax.Array, jax.Array]:
        def per_x(x: jax.Array) -> tuple[jax.Array, jax.Array]:
            logits = jax.vmap(model, in_axes=(0, None))(dataset.train_inputs, x)
            ce = jnp.mean(optax.softmax_cross_entropy_with_integer_labels(logits, dataset.train_targets))
            complexity = jnp.linalg.norm(model.target_params(x))
            return ce, complexity
        return jax.vmap(per_x)(xs)

    errors, complexities = _batch_metrics(x_samples)
    errors = np.array(errors)
    complexities = np.array(complexities)

    # Log-transform complexity for equal-width bins in log space
    log_cpx = np.log10(np.maximum(complexities, 0.1))
    x_min, x_max = np.log10(0.1), np.log10(xlim)

    fig, ax = plt.subplots(figsize=(7, 5))
    hb = ax.hexbin(
        log_cpx, errors,
        gridsize=25, cmap="plasma", mincnt=1,
        extent=[x_min, x_max, 0, ylim],
    )
    plt.colorbar(hb, ax=ax, label="count")
    ax.set_xlim(x_min, x_max)
    ax.set_ylim(0, ylim)

    # Label ticks with actual complexity values
    tick_vals = [v for v in [0.1, 1, 3, 10, 30, 100, 200, 500, 1000] if v <= xlim]
    ax.set_xticks([np.log10(v) for v in tick_vals])
    ax.set_xticklabels([str(int(v)) if v >= 1 else str(v) for v in tick_vals])

    ax.set_xlabel("target complexity (L2 norm, log scale)")
    ax.set_ylabel("train CE")
    ax.set_title(f"Error vs Complexity — epoch {epoch:,}")
    fig.tight_layout()
    out_path = out_dir / f"hexplot_{epoch:07d}.png"
    fig.savefig(str(out_path), dpi=130)
    plt.close(fig)


def _run_loop(
    model: ModularHNN,
    optimizer: optax.GradientTransformation,
    opt_state: optax.OptState,
    dataset: Any,
    cfg: GrokkingHNNConfig,
    n_epochs: int,
    start_epoch: int,
    existing_metrics: list[dict[str, Any]],
    rng: np.random.Generator,
    data_dir: Path,
) -> tuple[ModularHNN, list[dict[str, Any]]]:
    key = jax.random.PRNGKey(cfg.seed + start_epoch)

    shrink_bias = cfg.shrink_target in ("bias", "both")
    shrink_weight = cfg.shrink_target in ("weight", "both")
    shrink_factor = 1.0 - cfg.shrink_wd * cfg.lr

    @eqx.filter_jit
    def step(
        model: ModularHNN,
        opt_state: optax.OptState,
        inputs: jax.Array,
        targets: jax.Array,
        x_samples: jax.Array,
    ) -> tuple[ModularHNN, optax.OptState, jax.Array]:
        loss, grads = eqx.filter_value_and_grad(
            lambda m: _loss_and_metrics(
                m, inputs, targets, x_samples,
                cfg.lambda_target_decay, cfg.lambda_complexity,
                cfg.softmax_temp, cfg.softmin_temp,
            )[0]
        )(model)
        updates, new_state = optimizer.update(grads, opt_state, eqx.filter(model, eqx.is_array))
        model = eqx.apply_updates(model, updates)

        # Post-step multiplicative shrinkage — bypasses Adam, true AdamW-style
        # WD applied directly to the chosen carrier(s) of the target params.
        if shrink_bias and shrink_weight:
            last = model.stimulus_ffn.layers[-1]
            assert last.bias is not None
            model = eqx.tree_at(
                lambda m: (m.stimulus_ffn.layers[-1].weight, m.stimulus_ffn.layers[-1].bias),
                model,
                (last.weight * shrink_factor, last.bias * shrink_factor),
            )
        elif shrink_weight:
            model = eqx.tree_at(
                lambda m: m.stimulus_ffn.layers[-1].weight,
                model,
                model.stimulus_ffn.layers[-1].weight * shrink_factor,
            )
        elif shrink_bias:
            last_bias = model.stimulus_ffn.layers[-1].bias
            assert last_bias is not None
            model = eqx.tree_at(
                lambda m: m.stimulus_ffn.layers[-1].bias,
                model,
                last_bias * shrink_factor,
            )

        return model, new_state, loss

    @eqx.filter_jit
    def eval_metrics(
        model: ModularHNN,
        inputs: jax.Array,
        targets: jax.Array,
        x_samples: jax.Array,
    ) -> tuple[jax.Array, jax.Array]:
        _, acc, ce = _loss_and_metrics(model, inputs, targets, x_samples)
        return ce, acc

    if cfg.fixed_x:
        key, subkey = jax.random.split(key)
        _fixed_x_samples = jax.random.uniform(
            subkey, (cfg.n_mc, cfg.n_stimulus), minval=-1.0, maxval=1.0
        )

    # Independent of cfg.seed/fixed_x so it's identical across arms — makes
    # param_std/param_norm/bias_norm directly comparable across the ablation.
    probe_x = jax.random.uniform(
        jax.random.PRNGKey(cfg.probe_seed), (cfg.probe_n, cfg.n_stimulus),
        minval=-1.0, maxval=1.0,
    )

    metrics = list(existing_metrics)
    pbar = trange(n_epochs, desc="epochs")
    for i in pbar:
        epoch = start_epoch + i
        if cfg.fixed_x:
            x_samples = _fixed_x_samples
        else:
            key, subkey = jax.random.split(key)
            x_samples = jax.random.uniform(
                subkey, (cfg.n_mc, cfg.n_stimulus), minval=-1.0, maxval=1.0
            )
        model, opt_state, _ = step(
            model, opt_state, dataset.train_inputs, dataset.train_targets, x_samples
        )

        do_log = (epoch + 1) % cfg.log_interval == 0 or (start_epoch == 0 and i == 0)
        do_hex = cfg.hexplot_interval > 0 and (
            (epoch + 1) % cfg.hexplot_interval == 0 or (start_epoch == 0 and i == 0)
        )
        do_ckpt = cfg.checkpoint_interval > 0 and (
            (epoch + 1) % cfg.checkpoint_interval == 0 or (start_epoch == 0 and i == 0)
        )

        if do_ckpt:
            eqx.tree_serialise_leaves(
                str(data_dir / f"checkpoint_{epoch + 1:07d}.eqx"), model
            )

        if do_hex:
            _hexplot(model, dataset, cfg.n_stimulus, epoch + 1, data_dir,
                     xlim=cfg.hexplot_xlim, ylim=cfg.hexplot_ylim)

        if do_log:
            key, eval_key = jax.random.split(key)
            if cfg.fixed_x:
                x_eval = _fixed_x_samples
            else:
                x_eval = jax.random.uniform(
                    eval_key, (32, cfg.n_stimulus), minval=-1.0, maxval=1.0
                )
            tr_loss, tr_acc = eval_metrics(
                model, dataset.train_inputs, dataset.train_targets, x_eval
            )
            te_loss, te_acc = eval_metrics(
                model, dataset.test_inputs, dataset.test_targets, x_eval
            )
            per_x_te_acc = jax.vmap(
                lambda x: jnp.mean(
                    jnp.argmax(jax.vmap(model, in_axes=(0, None))(dataset.test_inputs, x), axis=-1)
                    == dataset.test_targets
                )
            )(x_eval)
            p_std = _param_std(model, x_eval)
            p_norm = _param_norm(model, x_eval)
            record: dict[str, Any] = {
                "epoch": epoch + 1,
                "train_loss": float(tr_loss),
                "test_loss": float(te_loss),
                "train_acc": float(tr_acc),
                "test_acc": float(te_acc),
                "test_acc_min": float(jnp.min(per_x_te_acc)),
                "test_acc_max": float(jnp.max(per_x_te_acc)),
                "param_std": p_std,
                "param_norm": p_norm,
                **_probe_metrics(model, probe_x),
            }
            metrics.append(record)
            pbar.set_postfix(
                tr=f"{float(tr_acc):.3f}",
                te=f"{float(te_acc):.3f}",
                pnorm=f"{p_norm:.2f}",
            )

    return model, metrics


def _setup(cfg: GrokkingHNNConfig) -> tuple[Any, ModularHNN]:
    key = jax.random.PRNGKey(cfg.seed)
    k_model, k_data = jax.random.split(key)
    dataset_cfg = ModularConfig(
        modulus=cfg.modulus, ops=(Op.ADD,), train_fraction=cfg.train_fraction
    )
    dataset = make_modular_dataset(dataset_cfg, k_data)
    in_dim = input_dim(dataset_cfg)
    model = make_modular_hypernetwork(
        k_model,
        in_dim=in_dim,
        out_dim=cfg.modulus,
        target_hidden=cfg.target_hidden,
        target_depth=cfg.target_depth,
        n_stimulus=cfg.n_stimulus,
        stim_ffn_hidden=cfg.stim_ffn_hidden,
        stim_ffn_depth=cfg.stim_ffn_depth,
        init_scale=cfg.init_scale,
        output_bias=cfg.output_bias,
    )
    return dataset, model


def train(cfg: GrokkingHNNConfig) -> ModularHNN:
    data_dir = Path(cfg.data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "config.json").write_text(json.dumps(dataclasses.asdict(cfg), indent=2))

    dataset, model = _setup(cfg)

    n_params = n_trainable_params(model)
    in_dim = dataset.train_inputs.shape[1]
    print(
        f"HNN:  in={in_dim}, stim={cfg.n_stimulus}, stim_ffn={cfg.stim_ffn_hidden}×{cfg.stim_ffn_depth}, "
        f"target_ffn={cfg.target_hidden}×{cfg.target_depth}, out={cfg.modulus}, params={n_params:,}"
    )
    print(
        f"Data: {dataset.train_inputs.shape[0]} train / "
        f"{dataset.test_inputs.shape[0]} test  ({cfg.train_fraction:.0%} split)"
    )
    print(f"n_mc={cfg.n_mc}, lambda_complexity={cfg.lambda_complexity}, weight_decay={cfg.weight_decay}, grad_clip={cfg.grad_clip}")
    print(f"output_bias={cfg.output_bias}, shrink_target={cfg.shrink_target}, shrink_wd={cfg.shrink_wd}, fixed_x={cfg.fixed_x}")

    optimizer = optax.chain(
        optax.clip_by_global_norm(cfg.grad_clip),
        optax.adamw(learning_rate=cfg.lr, weight_decay=cfg.weight_decay),
    )
    opt_state = optimizer.init(eqx.filter(model, eqx.is_array))
    rng = np.random.default_rng(cfg.seed)

    model, metrics = _run_loop(
        model, optimizer, opt_state, dataset, cfg,
        n_epochs=cfg.n_epochs, start_epoch=0, existing_metrics=[], rng=rng,
        data_dir=data_dir,
    )

    (data_dir / "metrics.json").write_text(json.dumps(metrics, indent=2))
    eqx.tree_serialise_leaves(str(data_dir / "model.eqx"), model)
    curve_path = data_dir / "grokking_hnn_curve.png"
    _plot(metrics, curve_path)
    print(f"\nMetrics → {data_dir / 'metrics.json'}")
    print(f"Curve   → {curve_path}")
    print(f"Model   → {data_dir / 'model.eqx'}")
    return model


def continue_train(cfg: GrokkingHNNConfig, additional_epochs: int) -> ModularHNN:
    """Load a saved checkpoint and continue training."""
    data_dir = Path(cfg.data_dir)
    model_path = data_dir / "model.eqx"
    metrics_path = data_dir / "metrics.json"

    if not model_path.exists():
        raise FileNotFoundError(f"No checkpoint at {model_path}. Run train() first.")

    dataset, template = _setup(cfg)
    model = eqx.tree_deserialise_leaves(str(model_path), template)
    existing_metrics: list[dict[str, Any]] = json.loads(metrics_path.read_text())
    start_epoch = existing_metrics[-1]["epoch"]

    print(f"Resuming from epoch {start_epoch}, running {additional_epochs} more")

    optimizer = optax.chain(
        optax.clip_by_global_norm(cfg.grad_clip),
        optax.adamw(learning_rate=cfg.lr, weight_decay=cfg.weight_decay),
    )
    opt_state = optimizer.init(eqx.filter(model, eqx.is_array))
    rng = np.random.default_rng(cfg.seed)

    model, metrics = _run_loop(
        model, optimizer, opt_state, dataset, cfg,
        n_epochs=additional_epochs, start_epoch=start_epoch,
        existing_metrics=existing_metrics, rng=rng,
        data_dir=data_dir,
    )

    (data_dir / "metrics.json").write_text(json.dumps(metrics, indent=2))
    eqx.tree_serialise_leaves(str(model_path), model)
    curve_path = data_dir / "grokking_hnn_curve.png"
    _plot(metrics, curve_path)
    print(f"\nMetrics → {data_dir / 'metrics.json'}")
    print(f"Curve   → {curve_path}")
    return model


def main() -> None:
    train(GrokkingHNNConfig())


def main_cont() -> None:
    continue_train(GrokkingHNNConfig(), additional_epochs=100_000)
