"""HyperNetwork grokking: modular addition via generated target classifiers.

Applies a HyperNetwork (HNN) to (a+b) mod 97 to establish a grokking baseline.
The stimulus FFN maps noise x ~ U[-1,1]^n_stimulus to the weights of a small
target FFN classifier. n_mc noise vectors are sampled each step; the mean
cross-entropy over them is the training loss.

With strong weight decay (weight_decay~1.0), the HNN's generated target
parameters are regularised indirectly, which is expected to produce a grokking
curve similar to the plain-FFN baseline — memorisation then delayed
generalisation.

Key knobs for adjusting grokking speed:
  weight_decay      — higher → slower memorisation, faster grok onset
  lambda_target_decay — direct L2 on generated params (augments weight_decay)
  train_fraction    — lower → slower grok (less signal for generalisation)
  target_hidden     — larger → more capacity, longer grok
  n_mc              — set to 1 for a single fixed-x run (pure reparameterisation
                       baseline); larger values average over x diversity

Entry points:
  god-grokking-hnn       — 200k epochs (full grok)
  god-grokking-hnn-cont  — continue from checkpoint
"""

import dataclasses
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import equinox as eqx
import jax
import jax.numpy as jnp
import numpy as np
import optax
from tqdm import trange

from god.datasets.modular import ModularConfig, Op, input_dim, make_modular_dataset
from god.models.modular_hnn import ModularHNN, make_modular_hypernetwork, n_trainable_params


@dataclass
class GrokkingHNNConfig:
    data_dir: str = "data/grokking_hnn"

    # Target FFN (generated by stimulus FFN)
    target_hidden: int = 32
    target_depth: int = 1

    # Stimulus FFN (learnable HNN weights)
    n_stimulus: int = 8
    stim_ffn_hidden: int = 8
    stim_ffn_depth: int = 1
    init_scale: float = 0.1

    # Data
    modulus: int = 97
    train_fraction: float = 0.5

    # Training — full-batch AdamW
    n_epochs: int = 200_000
    lr: float = 1e-3
    weight_decay: float = 0.01  # low: HNN is relatively unconstrained

    # L2 on generated target params — this is the primary grokking knob,
    # analogous to weight_decay on the standalone FFN baseline
    lambda_target_decay: float = 1.0

    # MC noise samples per step
    n_mc: int = 4
    # If True, sample x once at init and reuse every step (pure reparameterisation
    # baseline: HNN becomes equivalent to a directly-trained target FFN)
    fixed_x: bool = False

    # Log accuracy/loss every log_interval epochs
    log_interval: int = 2000

    # Reproducibility
    seed: int = 0


def _loss_and_metrics(
    model: ModularHNN,
    inputs: jax.Array,
    targets: jax.Array,
    x_samples: jax.Array,
    lambda_target_decay: float,
) -> tuple[jax.Array, jax.Array, jax.Array]:
    """Returns (loss, mean_accuracy, mean_ce_loss) averaged over MC samples."""

    def per_x(x: jax.Array) -> tuple[jax.Array, jax.Array]:
        logits = jax.vmap(model, in_axes=(0, None))(inputs, x)
        ce = jnp.mean(optax.softmax_cross_entropy_with_integer_labels(logits, targets))
        acc = jnp.mean(jnp.argmax(logits, axis=-1) == targets)
        return ce, acc

    ces, accs = jax.vmap(per_x)(x_samples)  # (n_mc,) each
    mean_ce = jnp.mean(ces)
    mean_acc = jnp.mean(accs)

    loss = mean_ce
    if lambda_target_decay > 0.0:
        l2 = jnp.mean(jax.vmap(lambda x: jnp.mean(model.target_params(x) ** 2))(x_samples))
        loss = loss + lambda_target_decay * l2

    return loss, mean_acc, mean_ce


def _param_std(model: ModularHNN, x_samples: jax.Array) -> float:
    """Std of generated target params across x_samples — measures stimulus collapse."""
    all_params = jax.vmap(model.target_params)(x_samples)
    return float(jnp.mean(jnp.std(all_params, axis=0)))


def _param_norm(model: ModularHNN, x_samples: jax.Array) -> float:
    """Mean L2 norm of generated target params across x_samples."""
    all_params = jax.vmap(model.target_params)(x_samples)
    return float(jnp.mean(jnp.linalg.norm(all_params, axis=1)))


def _plot(metrics: list[dict[str, Any]], out_path: Path) -> None:
    import matplotlib.pyplot as plt

    epochs = [m["epoch"] for m in metrics]
    train_acc = [m["train_acc"] for m in metrics]
    test_acc = [m["test_acc"] for m in metrics]
    has_diversity = "param_std" in metrics[0]

    n_rows = 2 if has_diversity else 1
    fig, axes = plt.subplots(n_rows, 1, figsize=(10, 4 * n_rows), squeeze=False)
    ax = axes[0, 0]

    ax.plot(epochs, train_acc, label="train accuracy", lw=1.5, color="tab:blue")
    ax.plot(epochs, test_acc, label="test accuracy (mean over x)", lw=1.5, color="tab:orange")
    if has_diversity:
        test_min = [m.get("test_acc_min", m["test_acc"]) for m in metrics]
        test_max = [m.get("test_acc_max", m["test_acc"]) for m in metrics]
        ax.fill_between(epochs, test_min, test_max, alpha=0.2, color="tab:orange", label="test acc min–max over x")
    ax.set_xscale("log")
    ax.set_ylim(-0.02, 1.02)
    ax.set_ylabel("accuracy")
    ax.set_title("Grokking HNN — (a+b) mod 97")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    if has_diversity:
        ax2 = axes[1, 0]
        ax2.plot(epochs, [m["param_std"] for m in metrics], lw=1.5, color="tab:purple")
        ax2.set_xscale("log")
        ax2.set_xlabel("epoch (log scale)")
        ax2.set_ylabel("param std across x")
        ax2.set_title("Target network diversity (→0 = collapsed to single solution)")
        ax2.grid(True, alpha=0.3)
    else:
        axes[0, 0].set_xlabel("epoch (log scale)")

    plt.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(str(out_path), dpi=150)
    plt.close(fig)


def _run_loop(
    model: ModularHNN,
    optimizer: optax.GradientTransformation,
    opt_state: optax.OptState,
    dataset: Any,
    cfg: GrokkingHNNConfig,
    n_epochs: int,
    start_epoch: int,
    existing_metrics: list[dict[str, Any]],
    rng: np.random.Generator,
) -> tuple[ModularHNN, list[dict[str, Any]]]:
    key = jax.random.PRNGKey(cfg.seed + start_epoch)

    @eqx.filter_jit
    def step(
        model: ModularHNN,
        opt_state: optax.OptState,
        inputs: jax.Array,
        targets: jax.Array,
        x_samples: jax.Array,
    ) -> tuple[ModularHNN, optax.OptState, jax.Array]:
        loss, grads = eqx.filter_value_and_grad(
            lambda m: _loss_and_metrics(m, inputs, targets, x_samples, cfg.lambda_target_decay)[0]
        )(model)
        updates, new_state = optimizer.update(grads, opt_state, eqx.filter(model, eqx.is_array))
        return eqx.apply_updates(model, updates), new_state, loss

    @eqx.filter_jit
    def eval_metrics(
        model: ModularHNN,
        inputs: jax.Array,
        targets: jax.Array,
        x_samples: jax.Array,
    ) -> tuple[jax.Array, jax.Array]:
        _, acc, ce = _loss_and_metrics(model, inputs, targets, x_samples, 0.0)
        return ce, acc

    # Fixed x: sample once, reuse every step (pure reparameterisation baseline)
    if cfg.fixed_x:
        key, subkey = jax.random.split(key)
        _fixed_x_samples = jax.random.uniform(
            subkey, (cfg.n_mc, cfg.n_stimulus), minval=-1.0, maxval=1.0
        )

    metrics = list(existing_metrics)
    pbar = trange(n_epochs, desc="epochs")
    for i in pbar:
        epoch = start_epoch + i
        if cfg.fixed_x:
            x_samples = _fixed_x_samples
        else:
            key, subkey = jax.random.split(key)
            x_samples = jax.random.uniform(
                subkey, (cfg.n_mc, cfg.n_stimulus), minval=-1.0, maxval=1.0
            )
        model, opt_state, _ = step(
            model, opt_state, dataset.train_inputs, dataset.train_targets, x_samples
        )

        if (epoch + 1) % cfg.log_interval == 0 or (start_epoch == 0 and i == 0):
            key, eval_key = jax.random.split(key)
            # Fixed-x: evaluate only on the training x (otherwise most eval x
            # produce untrained target networks, corrupting the accuracy signal)
            if cfg.fixed_x:
                x_eval = _fixed_x_samples
            else:
                x_eval = jax.random.uniform(
                    eval_key, (32, cfg.n_stimulus), minval=-1.0, maxval=1.0
                )
            tr_loss, tr_acc = eval_metrics(
                model, dataset.train_inputs, dataset.train_targets, x_eval
            )
            te_loss, te_acc = eval_metrics(
                model, dataset.test_inputs, dataset.test_targets, x_eval
            )
            # Per-x test accuracies to track diversity of generalisation
            per_x_te_acc = jax.vmap(
                lambda x: jnp.mean(
                    jnp.argmax(jax.vmap(model, in_axes=(0, None))(dataset.test_inputs, x), axis=-1)
                    == dataset.test_targets
                )
            )(x_eval)
            p_std = _param_std(model, x_eval)
            p_norm = _param_norm(model, x_eval)
            record: dict[str, Any] = {
                "epoch": epoch + 1,
                "train_loss": float(tr_loss),
                "test_loss": float(te_loss),
                "train_acc": float(tr_acc),
                "test_acc": float(te_acc),
                "test_acc_min": float(jnp.min(per_x_te_acc)),
                "test_acc_max": float(jnp.max(per_x_te_acc)),
                "param_std": p_std,
                "param_norm": p_norm,
            }
            metrics.append(record)
            pbar.set_postfix(
                tr=f"{float(tr_acc):.3f}",
                te=f"{float(te_acc):.3f}",
                pnorm=f"{p_norm:.2f}",
            )

    return model, metrics


def _setup(cfg: GrokkingHNNConfig) -> tuple[Any, ModularHNN]:
    key = jax.random.PRNGKey(cfg.seed)
    k_model, k_data = jax.random.split(key)
    dataset_cfg = ModularConfig(
        modulus=cfg.modulus, ops=(Op.ADD,), train_fraction=cfg.train_fraction
    )
    dataset = make_modular_dataset(dataset_cfg, k_data)
    in_dim = input_dim(dataset_cfg)
    model = make_modular_hypernetwork(
        k_model,
        in_dim=in_dim,
        out_dim=cfg.modulus,
        target_hidden=cfg.target_hidden,
        target_depth=cfg.target_depth,
        n_stimulus=cfg.n_stimulus,
        stim_ffn_hidden=cfg.stim_ffn_hidden,
        stim_ffn_depth=cfg.stim_ffn_depth,
        init_scale=cfg.init_scale,
    )
    return dataset, model


def train(cfg: GrokkingHNNConfig) -> ModularHNN:
    data_dir = Path(cfg.data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "config.json").write_text(json.dumps(dataclasses.asdict(cfg), indent=2))

    dataset, model = _setup(cfg)

    n_params = n_trainable_params(model)
    in_dim = dataset.train_inputs.shape[1]
    print(
        f"HNN:  in={in_dim}, stim={cfg.n_stimulus}, stim_ffn={cfg.stim_ffn_hidden}×{cfg.stim_ffn_depth}, "
        f"target_ffn={cfg.target_hidden}×{cfg.target_depth}, out={cfg.modulus}, params={n_params:,}"
    )
    print(
        f"Data: {dataset.train_inputs.shape[0]} train / "
        f"{dataset.test_inputs.shape[0]} test  ({cfg.train_fraction:.0%} split)"
    )
    print(f"n_mc={cfg.n_mc}, weight_decay={cfg.weight_decay}, lambda_target_decay={cfg.lambda_target_decay}")

    optimizer = optax.adamw(learning_rate=cfg.lr, weight_decay=cfg.weight_decay)
    opt_state = optimizer.init(eqx.filter(model, eqx.is_array))
    rng = np.random.default_rng(cfg.seed)

    model, metrics = _run_loop(
        model, optimizer, opt_state, dataset, cfg,
        n_epochs=cfg.n_epochs, start_epoch=0, existing_metrics=[], rng=rng,
    )

    (data_dir / "metrics.json").write_text(json.dumps(metrics, indent=2))
    eqx.tree_serialise_leaves(str(data_dir / "model.eqx"), model)
    curve_path = data_dir / "grokking_hnn_curve.png"
    _plot(metrics, curve_path)
    print(f"\nMetrics → {data_dir / 'metrics.json'}")
    print(f"Curve   → {curve_path}")
    print(f"Model   → {data_dir / 'model.eqx'}")
    return model


def continue_train(cfg: GrokkingHNNConfig, additional_epochs: int) -> ModularHNN:
    """Load a saved checkpoint and continue training."""
    data_dir = Path(cfg.data_dir)
    model_path = data_dir / "model.eqx"
    metrics_path = data_dir / "metrics.json"

    if not model_path.exists():
        raise FileNotFoundError(f"No checkpoint at {model_path}. Run train() first.")

    dataset, template = _setup(cfg)
    model = eqx.tree_deserialise_leaves(str(model_path), template)
    existing_metrics: list[dict[str, Any]] = json.loads(metrics_path.read_text())
    start_epoch = existing_metrics[-1]["epoch"]

    print(f"Resuming from epoch {start_epoch}, running {additional_epochs} more")

    optimizer = optax.adamw(learning_rate=cfg.lr, weight_decay=cfg.weight_decay)
    opt_state = optimizer.init(eqx.filter(model, eqx.is_array))
    rng = np.random.default_rng(cfg.seed)

    model, metrics = _run_loop(
        model, optimizer, opt_state, dataset, cfg,
        n_epochs=additional_epochs, start_epoch=start_epoch,
        existing_metrics=existing_metrics, rng=rng,
    )

    (data_dir / "metrics.json").write_text(json.dumps(metrics, indent=2))
    eqx.tree_serialise_leaves(str(model_path), model)
    curve_path = data_dir / "grokking_hnn_curve.png"
    _plot(metrics, curve_path)
    print(f"\nMetrics → {data_dir / 'metrics.json'}")
    print(f"Curve   → {curve_path}")
    return model


def main() -> None:
    train(GrokkingHNNConfig())


def main_cont() -> None:
    continue_train(GrokkingHNNConfig(), additional_epochs=100_000)
